name: GitHub-Profile-3D-Contrib

on:
  schedule: # Change this to a convenient time, e.g., 09:00 JST == 00:00 UTC
    - cron: "0 0 * * *"  # Adjust the cron time as needed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          USERNAME: ${{ github.ddyankov28}}
          # Uncomment these lines if you want to set optional parameters
          # MAX_REPOS: 50  # Optional: Set max repos, default is 100
          # SETTING_JSON: .path/to/your/settings.json  # Optional: Specify settings JSON if needed
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
